using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Resources;
using System.Text;
using System.Xml.Linq;

internal static class Program
{
    public static int Main(string[] args)
    {
        try
        {
            var options = ParseOptions(args);
            var source = Required(options, "src");
            var output = Required(options, "out");
            var resources = ReadStringResources(source);
            if (options.ContainsKey("resource"))
            {
                WriteResource(output, resources);
                return 0;
            }

            var namespaceName = Required(options, "namespace");
            var className = Required(options, "class");
            var accessibility = Required(options, "accessibility");
            var constants = options.ContainsKey("constants");

            ValidateIdentifier(className, "class name");
            foreach (var resource in resources)
            {
                ValidateIdentifier(resource.Name, "resource name");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(output) ?? ".");
            File.WriteAllText(output, Generate(namespaceName, className, accessibility, constants, resources), new UTF8Encoding(false));
            return 0;
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception.Message);
            return 1;
        }
    }

    private static IReadOnlyList<ResourceEntry> ReadStringResources(string source)
    {
        var document = XDocument.Load(source, LoadOptions.PreserveWhitespace);
        return document.Root!
            .Elements("data")
            .Where(element => element.Attribute("type") is null && element.Attribute("mimetype") is null)
            .Select(element => new ResourceEntry(
                element.Attribute("name")?.Value ?? throw new InvalidOperationException("Resource data element is missing a name."),
                element.Element("value")?.Value ?? string.Empty))
            .ToArray();
    }

    private static void WriteResource(string output, IReadOnlyList<ResourceEntry> resources)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(output) ?? ".");
        using var writer = new ResourceWriter(output);
        foreach (var resource in resources)
        {
            writer.AddResource(resource.Name, resource.Value);
        }
    }

    private static string Generate(string namespaceName, string className, string accessibility, bool constants, IReadOnlyList<ResourceEntry> resources)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Reflection;");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
        builder.AppendLine($"    {accessibility} static partial class {className}");
        builder.AppendLine("    {");
        builder.AppendLine("        private static global::System.Resources.ResourceManager? s_resourceManager;");
        builder.AppendLine($"        {accessibility} static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof({className}))); ");
        builder.AppendLine($"        {accessibility} static global::System.Globalization.CultureInfo? Culture {{ get; set; }}");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine("        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(\"defaultValue\")]");
        builder.AppendLine("        internal static string? GetResourceString(string resourceKey, string? defaultValue = null) => ResourceManager.GetString(resourceKey, Culture) ?? defaultValue;");
        foreach (var resource in resources)
        {
            builder.AppendLine($"        /// <summary>{EscapeXmlDoc(resource.Value)}</summary>");
            if (constants)
            {
                builder.AppendLine($"        {accessibility} const string @{resource.Name} = {CSharpString(resource.Name)};");
            }
            else
            {
                builder.AppendLine($"        {accessibility} static string @{resource.Name} => GetResourceString({CSharpString(resource.Name)}, {CSharpString(resource.Value)})!;");
            }
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static Dictionary<string, string> ParseOptions(string[] args)
    {
        var options = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var index = 0; index < args.Length; index++)
        {
            var key = args[index];
            if (!key.StartsWith("--", StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Unexpected argument: {key}");
            }

            key = key[2..];
            if (key is "constants" or "resource")
            {
                options[key] = "true";
                continue;
            }

            if (++index >= args.Length)
            {
                throw new InvalidOperationException($"Missing value for argument: --{key}");
            }

            options[key] = args[index];
        }

        return options;
    }

    private static string Required(Dictionary<string, string> options, string name)
    {
        if (!options.TryGetValue(name, out var value) || string.IsNullOrWhiteSpace(value))
        {
            throw new InvalidOperationException($"Missing required option --{name}.");
        }

        return value;
    }

    private static void ValidateIdentifier(string value, string description)
    {
        if (string.IsNullOrWhiteSpace(value) || !(char.IsLetter(value[0]) || value[0] == '_') || value.Any(character => !(char.IsLetterOrDigit(character) || character == '_')))
        {
            throw new InvalidOperationException($"Invalid C# identifier for {description}: {value}");
        }
    }

    private static string CSharpString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            builder.Append(character switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => character.ToString()
            });
        }
        builder.Append('"');
        return builder.ToString();
    }

    private static string EscapeXmlDoc(string value)
    {
        return value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
    }

    private sealed record ResourceEntry(string Name, string Value);
}