namespace RulesDotnet.Tests
{
    /// <summary>A first-party dependency of the generator, which travels with it into its package.</summary>
    public static class GeneratorSupport
    {
        public const string Source = "// <auto-generated/>\nnamespace RulesDotnet.Tests { public static class Packed { } }\n";
    }
}
