image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: Bazel
    before: "./.gitpod/gitpod-init.sh"
    init: |
      # Until this issue is fixed: https://github.com/gitpod-io/gitpod/issues/8901
      mkdir -p $DOTNET_ROOT && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION --install-dir $DOTNET_ROOT
      dotnet tool install --tool-path /workspace/dotnet-tools --version 4.7.3 fantomas-tool || true
      dotnet tool install --tool-path /workspace/dotnet-tools paket || true
      bazel build //...

vscode:
  extensions:
    - BazelBuild.vscode-bazel
    - Ionide.Ionide-fsharp
    - muhammad-sammy.csharp

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
