# trusty beta image has jdk8, gcc4.8.4
dist: bionic
sudo: required
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux
  - osx

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
      brew cask install homebrew/cask-versions/adoptopenjdk8
      brew install bazel coreutils
      brew cask install mono-mdk
    else
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
      sudo apt install apt-transport-https
      echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list    
      sudo apt update
      sudo apt install -y mono-devel libunwind8-dev bazel 
      OS=linux
    fi

script:
  - |
    bazel version

  - |
    export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/
    mono --version

  - |
    export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/
    bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m build --spawn_strategy=standalone //...

  - |
    export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/
    bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m run --spawn_strategy=standalone //tests/examples/example_binary:hello.exe

  - |
    export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/
    bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m run --spawn_strategy=standalone //tests/examples/example_binary:v2.1.200_hello-core.exe

  - |
    export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/
    bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m test --test_summary=detailed --spawn_strategy=standalone --test_output=all //... 
    
notifications:
  email: false