version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

clone_script:
- cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: cd %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
- cmd: git submodule update --init --recursive

install:
  - choco install mono
  - choco install bazel
  
build_script:
  - ver
  - bazel  --batch --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m build -s  --local_resources=400,1,1.0  //...
  - bazel  --batch --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m run -s   --local_resources=400,1,1.0  //tests/examples/example_binary:hello
  - bazel  --batch --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m test --test_summary=detailed --test_output=all -s --local_resources=400,1,1.0  //...

test: off

deploy: off

