jobs:
- job: BuildAndTest  
  strategy:
    matrix:
      linux:
        poolName: 'Azure Pipelines'
        vmImage: 'ubuntu-16.04'       
        system: 'linux'
      windows:
        poolName: 'home'
        vmImage: ''
        system: 'windows'
      mac:
        poolName: 'Azure Pipelines'
        vmImage: 'macOS-10.13'
        system: 'mac'
  pool:
    name: $(poolName)
    vmImage: $(vmImage)

  steps:
    - script: |
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y bazel
      displayName: 'Install dependencies'
      condition: and(succeeded(), eq(variables['system'], 'linux'))

    - script: |
        brew install bazel coreutils
      displayName: 'Install dependencies'
      condition: and(succeeded(), eq(variables['system'], 'mac'))

    - script: |
        brew cask install mono-mdk
      displayName: 'Install mono'
      condition: and(succeeded(), eq(variables['system'], 'windows'))

    - script: |
        del c:\users\tomek\_bazel_tomek\sfs5eyg3\server\server_info.rawproto
      displayName: 'Delete files for windows'
      condition: and(succeeded(), eq(variables['system'], 'windows'))

        

    - script: |
        bazel version
      displayName: 'Show bazel version'
    - script: |
        dotnet --info
      displayName: 'Show dotnet version'
    - script: |
        mono --version
      displayName: 'Show mono version'

