using Microsoft.CodeAnalysis;

namespace Example.Generator
{
    /// <summary>Adds a `Greetings.Default` constant to every compilation that references this package.</summary>
    [Generator]
    public sealed class GreetingGenerator : ISourceGenerator
    {
        private const string Source = @"// <auto-generated/>
namespace Example
{
    /// <summary>Greetings this project can use.</summary>
    public static class Greetings
    {
        /// <summary>The greeting a project gets for free.</summary>
        public const string Default = ""Hello"";
    }
}
";

        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context) =>
            context.AddSource("Greetings.g.cs", Source);
    }
}
