load(
    "//dotnet/private/rules/csharp:binary.bzl",
    "bootstrap_tool_binary",
)

bootstrap_tool_binary(
    name = "apphost_shimmer",
    srcs = [
        "AppHostShellShimMaker.cs",
        "Program.cs",
    ],
    include_host_model_dll = True,
    target_frameworks = ["net10.0"],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
