using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

internal static class Program
{
    private static int Main(string[] args)
    {
        if (args.Length < 4)
        {
            Console.Error.WriteLine("usage: stamp_assembly_info --language <csharp|fsharp> --out <path> [--assembly-name <name> --target-framework <tfm> --configuration <configuration>] [--metadata <key=value>] [status-file...]");
            return 1;
        }

        string? language = null;
        string? output = null;
        string? assemblyName = null;
        string? targetFramework = null;
        string? configuration = null;
        var metadata = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var statusFiles = new List<string>();

        for (var i = 0; i < args.Length; i++)
        {
            switch (args[i])
            {
                case "--language":
                    language = args[++i];
                    break;
                case "--out":
                    output = args[++i];
                    break;
                case "--assembly-name":
                    assemblyName = args[++i];
                    break;
                case "--target-framework":
                    targetFramework = args[++i];
                    break;
                case "--configuration":
                    configuration = args[++i];
                    break;
                case "--metadata":
                    var entry = args[++i];
                    var separator = entry.IndexOf('=');
                    if (separator <= 0)
                    {
                        throw new ArgumentException("Assembly metadata must be key=value.");
                    }
                    metadata[entry[..separator]] = entry[(separator + 1)..];
                    break;
                default:
                    statusFiles.Add(args[i]);
                    break;
            }
        }

        if (language is not ("csharp" or "fsharp") || string.IsNullOrEmpty(output))
        {
            Console.Error.WriteLine("language must be csharp or fsharp, and --out is required");
            return 1;
        }

        var attributes = new SortedDictionary<string, string>(StringComparer.Ordinal);
        if (assemblyName != null)
        {
            attributes["AssemblyCompany"] = assemblyName;
            attributes["AssemblyConfiguration"] = configuration ?? "Release";
            attributes["AssemblyFileVersion"] = "1.0.0.0";
            attributes["AssemblyInformationalVersion"] = "1.0.0";
            attributes["AssemblyProduct"] = assemblyName;
            attributes["AssemblyTitle"] = assemblyName;
            attributes["AssemblyVersion"] = "1.0.0.0";
        }
        foreach (var statusFile in statusFiles)
        {
            ReadStatusFile(statusFile, attributes);
        }

        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        File.WriteAllText(output, GenerateSource(language, attributes, metadata, targetFramework), Encoding.UTF8);
        return 0;
    }

    private static void ReadStatusFile(string path, SortedDictionary<string, string> attributes)
    {
        foreach (var line in File.ReadLines(path))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var split = line.IndexOfAny([' ', '\t']);
            var key = split < 0 ? line : line[..split];
            var value = split < 0 ? string.Empty : line[(split + 1)..].TrimStart();

            if (key.StartsWith("STABLE_", StringComparison.Ordinal))
            {
                key = key["STABLE_".Length..];
            }

            if (!key.StartsWith("ASSEMBLY_", StringComparison.Ordinal))
            {
                continue;
            }

            attributes[ToPascalCase(key)] = value;
        }
    }

    private static string GenerateSource(string language, SortedDictionary<string, string> attributes,
        SortedDictionary<string, string> metadata, string? targetFramework)
    {
        var builder = new StringBuilder();

        if (language == "csharp")
        {
            builder.AppendLine("// <auto-generated />");
        }
        else
        {
            builder.AppendLine("namespace RulesDotnet.GeneratedAssemblyInfo");
            builder.AppendLine();
        }

        foreach (var (attribute, value) in attributes)
        {
            AppendAttribute(builder, language, $"System.Reflection.{attribute}(\"{Escape(value)}\")");
        }
        foreach (var (key, value) in metadata)
        {
            AppendAttribute(builder, language, $"System.Reflection.AssemblyMetadata(\"{Escape(key)}\", \"{Escape(value)}\")");
        }
        if (targetFramework != null)
        {
            AppendAttribute(builder, language, $"System.Runtime.Versioning.TargetFramework(\"{GetFrameworkName(targetFramework)}\")");
        }
        return builder.ToString();
    }

    private static void AppendAttribute(StringBuilder builder, string language, string attribute)
    {
        if (language == "csharp")
        {
            builder.AppendLine($"[assembly: {attribute}]");
        }
        else
        {
            builder.AppendLine($"[<assembly: {attribute}>]");
            builder.AppendLine("do ()");
            builder.AppendLine();
        }
    }

    private static string GetFrameworkName(string framework)
    {
        if (framework.StartsWith("netstandard", StringComparison.Ordinal))
        {
            return ".NETStandard,Version=v" + framework["netstandard".Length..];
        }
        if (framework.StartsWith("netcoreapp", StringComparison.Ordinal))
        {
            return ".NETCoreApp,Version=v" + framework["netcoreapp".Length..];
        }
        var version = framework["net".Length..];
        return version.Contains('.')
            ? ".NETCoreApp,Version=v" + version
            : ".NETFramework,Version=v" + string.Join(".", version.ToCharArray());
    }

    private static string ToPascalCase(string key)
    {
        var builder = new StringBuilder();
        foreach (var part in key.Split('_', StringSplitOptions.RemoveEmptyEntries))
        {
            builder.Append(char.ToUpperInvariant(part[0]));
            builder.Append(part[1..].ToLowerInvariant());
        }

        return builder.ToString();
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
             .Replace("\"", "\\\"", StringComparison.Ordinal)
             .Replace("\r", "\\r", StringComparison.Ordinal)
             .Replace("\n", "\\n", StringComparison.Ordinal);
}
