"GENERATED"

load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")

def rules_dotnet_framework_override_not_provided_tests():
    "rules_dotnet_framework_override_not_provided_tests"
    nuget_repo(
        name = "paket.rules_dotnet_framework_override_not_provided_tests",
        packages = [
            {"name": "Microsoft.Bcl.Cryptography", "id": "Microsoft.Bcl.Cryptography", "version": "10.0.5", "sha512": "sha512-Q3SPgw4lwBP5bHl5CJki2+YXKYoP0uug1js4Y4qL5dHufaUcHSFPv2H9Y89N6lhBd+DBab+gQkj3Aw/qp/8vcA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": ["System.Formats.Asn1"], "net462": ["System.Formats.Asn1"], "net47": ["System.Formats.Asn1"], "net471": ["System.Formats.Asn1"], "net472": ["System.Formats.Asn1"], "net48": ["System.Formats.Asn1"], "net5.0": ["System.Formats.Asn1"], "net6.0": ["System.Formats.Asn1"], "net7.0": ["System.Formats.Asn1"], "net8.0": ["System.Formats.Asn1"], "net9.0": [], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": ["System.Formats.Asn1"], "netcoreapp2.1": ["System.Formats.Asn1"], "netcoreapp2.2": ["System.Formats.Asn1"], "netcoreapp3.0": ["System.Formats.Asn1"], "netcoreapp3.1": ["System.Formats.Asn1"], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": ["System.Formats.Asn1"], "netstandard2.1": ["System.Formats.Asn1"]}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "System.Formats.Asn1", "id": "System.Formats.Asn1", "version": "10.0.5", "sha512": "sha512-oB9y1SSU5t0rcZPO0l4I7YWSce+9+oow05sZ7xFpL/9qMH2s3umavWtQmDYqN7xCD7nhNt5gK07zBdC36NMwUQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": [], "net462": [], "net47": [], "net471": [], "net472": [], "net48": [], "net5.0": [], "net6.0": [], "net7.0": [], "net8.0": [], "net9.0": [], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": [], "netcoreapp2.1": [], "netcoreapp2.2": [], "netcoreapp3.0": [], "netcoreapp3.1": [], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": [], "netstandard2.1": []}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "System.Security.Cryptography.Pkcs", "id": "System.Security.Cryptography.Pkcs", "version": "10.0.5", "sha512": "sha512-gJqTnoYtrGrXeYYCOvAbUSpLiqVy1LZjXNAuqx12B8tzhUpUeZ9yVPzZgwmJC/nzo5cz2SCEWry5LI1m0pL8mA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "net462": ["Microsoft.Bcl.Cryptography"], "net47": ["Microsoft.Bcl.Cryptography"], "net471": ["Microsoft.Bcl.Cryptography"], "net472": ["Microsoft.Bcl.Cryptography"], "net48": ["Microsoft.Bcl.Cryptography"], "net5.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "net6.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "net7.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "net8.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "net9.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netcoreapp2.1": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netcoreapp2.2": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netcoreapp3.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netcoreapp3.1": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"], "netstandard2.1": ["Microsoft.Bcl.Cryptography", "System.Formats.Asn1"]}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "System.Security.Cryptography.Xml", "id": "System.Security.Cryptography.Xml", "version": "9.0.0", "sha512": "sha512-mwVmVCR0Z+3WQx/Iw9PhKyN/ineNJkx7ypNM7j8EQKABZyVxobdS/Mfi3WwgCy0GfZpjLMoulsW3SDHaGG9XMA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": ["System.Security.Cryptography.Pkcs"], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "net462": ["Microsoft.Bcl.Cryptography"], "net47": ["Microsoft.Bcl.Cryptography"], "net471": ["Microsoft.Bcl.Cryptography"], "net472": ["Microsoft.Bcl.Cryptography"], "net48": ["Microsoft.Bcl.Cryptography"], "net5.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "net6.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "net7.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "net8.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "net9.0": ["System.Security.Cryptography.Pkcs"], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netcoreapp2.1": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netcoreapp2.2": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netcoreapp3.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netcoreapp3.1": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"], "netstandard2.1": ["Microsoft.Bcl.Cryptography", "System.Security.Cryptography.Pkcs"]}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
        ],
    )
