"""
Rules to load all the .NET SDK & framework dependencies of rules_dotnet.
"""

load("//dotnet/private:toolchains_repo.bzl", "DOTNET_TOOLCHAIN_TYPE", "PLATFORMS", "toolchains_repo")
load("//dotnet/private/sdk:versions.bzl", "TOOL_VERSIONS")

########
# Remaining content of the file is only used to support toolchains.
########
_DOC = "Fetch external tools needed for dotnet toolchain"
_ATTRS = {
    "dotnet_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _dotnet_repo_impl(repository_ctx):
    url = TOOL_VERSIONS[repository_ctx.attr.dotnet_version][repository_ctx.attr.platform]["url"]
    repository_ctx.download_and_extract(
        url = url,
        integrity = TOOL_VERSIONS[repository_ctx.attr.dotnet_version][repository_ctx.attr.platform]["hash"],
    )
    build_content = """#Generated by dotnet/repositories.bzl
load("@rules_dotnet//dotnet:toolchain.bzl", "dotnet_toolchain")
load("@rules_dotnet//dotnet:defs.bzl", "import_dll")

filegroup(
    name = "csc_binary",
    srcs = [
        "sdk/{sdk_version}/Roslyn/bincore/csc.dll",
    ],
    data = glob([
        "sdk/{sdk_version}/Roslyn/bincore/**/*",
        "host/**/*",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "runtime",
    srcs = select({{
        "@bazel_tools//src/conditions:windows": ["dotnet.exe"],
        "//conditions:default": ["dotnet"],
    }}),
    data = glob([
        "host/**/*",
        "sdk/**/*",
        "shared/Microsoft.AspNetCore.App/**/*",
        "shared/Microsoft.NETCore.App/**/*",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "runtime_host",
    srcs = select({{
        "@bazel_tools//src/conditions:windows": ["dotnet.exe"],
        "//conditions:default": ["dotnet"],
    }}),
    data = glob([
        "host/**/*",
        # Every shared framework, not just Microsoft.NETCore.App: a binary built
        # with `project_sdk = "web"` asks its runtimeconfig for
        # Microsoft.AspNetCore.App.
        "shared/**/*",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "compiler_host",
    srcs = select({{
        "@bazel_tools//src/conditions:windows": ["dotnet.exe"],
        "//conditions:default": ["dotnet"],
    }}),
    data = glob([
        "host/**/*",
        "shared/Microsoft.NETCore.App/**/*",
    ]),
    visibility = ["//visibility:public"],
)

import_dll(
    name = "host_model",
    version = "{runtime_version}",
    dll = "sdk/{sdk_version}/Microsoft.NET.HostModel.dll",
)

# The MSBuild interfaces a task is written against, so that a tool of ours can
# run an SDK build task directly. Taken from the SDK rather than NuGet, so the
# interfaces always match the tasks.
import_dll(
    name = "msbuild_framework",
    version = "{runtime_version}",
    dll = "sdk/{sdk_version}/Microsoft.Build.Framework.dll",
)

import_dll(
    name = "msbuild_utilities",
    version = "{runtime_version}",
    dll = "sdk/{sdk_version}/Microsoft.Build.Utilities.Core.dll",
)

# The tasks that implement scoped CSS, and the CSS parser they use. The net472
# copies are for MSBuild.exe on .NET Framework; ours run on the .NET host.
filegroup(
    name = "static_web_assets_tasks",
    srcs = glob(
        ["sdk/{sdk_version}/Sdks/Microsoft.NET.Sdk.StaticWebAssets/tasks/**/*.dll"],
        exclude = ["**/net472/**"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)

# The assemblies `Microsoft.NET.Sdk.Razor` puts into `@(Analyzer)` to compile
# `.razor` and `.cshtml`.
filegroup(
    name = "razor_source_generators",
    srcs = glob(
        ["sdk/{sdk_version}/Sdks/Microsoft.NET.Sdk.Razor/source-generators/*.dll"],
        allow_empty = True,
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "fsc_binary",
    # We glob both fsc.dll and fsc.exe for backwards compatibility
    # Pre .Net 5.0 the file was called fsc.exe but has been changed to fsc.dll
    srcs = glob(
        [
            "sdk/**/FSharp/fsc.dll*",
            "sdk/**/FSharp/fsc.exe*",
        ],
        allow_empty = True,
    ) or fail("glob is empty"),
    data = glob([
        "host/**/*",
        "sdk/{sdk_version}/FSharp/**/*.dll",
    ]) + [
        "sdk/{sdk_version}/FSharp/fsc.runtimeconfig.json",
    ],
    visibility = ["//visibility:public"],
)

dotnet_toolchain(
    name = "dotnet_toolchain", 
    runtime = ":runtime",
    runtime_host = ":runtime_host",
    compiler_host = ":compiler_host",
    csharp_compiler = ":csc_binary",
    fsharp_compiler = ":fsc_binary",
    host_model = ":host_model",
    razor_source_generators = ":razor_source_generators",
    static_web_assets_tasks = ":static_web_assets_tasks",
    msbuild_dlls = [":msbuild_framework", ":msbuild_utilities"],
    os = "{os}",
    sdk_version = "{sdk_version}",
    runtime_version = "{runtime_version}",
    runtime_tfm = "{runtime_tfm}",
    csharp_default_version = "{csharp_default_version}",
    fsharp_default_version = "{fsharp_default_version}",
    visibility = ["//visibility:public"],
)
""".format(
        os = PLATFORMS[repository_ctx.attr.platform].os,
        sdk_version = repository_ctx.attr.dotnet_version,
        runtime_version = TOOL_VERSIONS[repository_ctx.attr.dotnet_version]["runtimeVersion"],
        runtime_tfm = TOOL_VERSIONS[repository_ctx.attr.dotnet_version]["runtimeTfm"],
        csharp_default_version = TOOL_VERSIONS[repository_ctx.attr.dotnet_version]["csharpDefaultVersion"],
        fsharp_default_version = TOOL_VERSIONS[repository_ctx.attr.dotnet_version]["fsharpDefaultVersion"],
    )

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

dotnet_repositories = repository_rule(
    _dotnet_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

def _sdk_repo_base(dotnet_version):
    return "dotnet_sdk.{}".format(dotnet_version)

def dotnet_sdk_repositories(dotnet_version, **kwargs):
    """Declares the per-platform repositories holding one .Net SDK.

    Named after the SDK version rather than the toolchain they back, so that two
    toolchains pinned to the same version share one download and one extraction,
    and so a compile's action key turns on the SDK it used rather than on which
    toolchain resolved it.

    Args:
        dotnet_version: The .Net SDK version to fetch, e.g. 8.0.100.
        **kwargs: passed to each dotnet_repositories call
    """
    for platform in PLATFORMS.keys():
        dotnet_repositories(
            name = "{}_{}".format(_sdk_repo_base(dotnet_version), platform),
            platform = platform,
            dotnet_version = dotnet_version,
            **kwargs
        )

def dotnet_toolchains_repo(name, dotnet_version, toolchain_type = DOTNET_TOOLCHAIN_TYPE):
    """Declares the repository of `toolchain` targets for one .Net SDK.

    Holds only the `toolchain` targets Bazel has to analyze up front; the SDK
    itself stays in the repositories `dotnet_sdk_repositories` declares, which
    are fetched only once a build actually needs them.

    Args:
        name: The name of the generated repository.
        dotnet_version: The .Net SDK version the toolchains point at.
        toolchain_type: The toolchain type the generated toolchains register for.
    """
    toolchains_repo(
        name = name,
        toolchain_type = toolchain_type,
        sdk_repository_name = _sdk_repo_base(dotnet_version),
    )
