"""
Actions for compiling targets with F#.
"""

load("@bazel_skylib//lib:dicts.bzl", "dicts")
load(
    "//dotnet/private:common.bzl",
    "add_resource_args",
    "collect_compile_info",
    "copy_files_to_dir",
    "format_ref_arg",
    "framework_preprocessor_symbols",
    "fsharp_ref_assemblies_are_deterministic",
    "generate_warning_args",
    "get_framework_version_info",
    "is_core_framework",
    "is_standard_framework",
    "use_highentropyva",
)
load("//dotnet/private:nuget_version.bzl", "DEFAULT_ASSEMBLY_VERSION", "nuget_version")
load(
    "//dotnet/private:providers.bzl",
    "DotnetAssemblyCompileInfo",
    "DotnetAssemblyRuntimeInfo",
)
load("//dotnet/private/icu:settings.bzl", "globalization_env", "icu_wrapper_arguments")

def _format_targetprofile(tfm):
    if is_standard_framework(tfm):
        return "--targetprofile:netstandard"

    if is_core_framework(tfm):
        return "--targetprofile:netcore"

    return "--targetprofile:mscorlib"

def _write_internals_visible_to_fsharp(actions, label_name, dll_name, others):
    """Write a .fs file containing InternalsVisibleTo attributes.

    Letting Bazel see which assemblies we are going to have InternalsVisibleTo
    allows for more robust caching of compiles.

    Args:
      actions: An actions module, usually from ctx.actions.
      label_name: The label name
      dll_name: The assembly name.
      others: The names of other assemblies.

    Returns:
      A File object for a generated .fs file
    """

    if len(others) == 0:
        return None

    content = """
module AssemblyInfo

"""
    for other in others:
        content += """
[<assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\"%s\")>]
do()

""" % other

    output = actions.declare_file("%s/%s/internalsvisibleto.fs" % (label_name, dll_name))
    actions.write(output, content)

    return output

def _write_assembly_version_fsharp(actions, label_name, dll_name, version):
    """Write a .fs file carrying the assembly version attributes.

    Args:
      actions: An actions module, usually from ctx.actions.
      label_name: The label name.
      dll_name: The assembly name.
      version: The target's `version` attribute; "" when unset.

    Returns:
      A File object for a generated .fs file, or None when there is no version.
    """
    if not version:
        return None

    # Fails on an invalid version, which is the earliest point that can say so.
    numeric = nuget_version.assembly_version(version)

    content = """// Generated by rules_dotnet from the target's `version` attribute.
module RulesDotnetAssemblyVersionInfo

[<assembly: System.Reflection.AssemblyVersion("%s")>]
[<assembly: System.Reflection.AssemblyFileVersion("%s")>]
[<assembly: System.Reflection.AssemblyInformationalVersion("%s")>]
do ()
""" % (numeric, numeric, version)

    output = actions.declare_file("%s/%s/assemblyinfo.fs" % (label_name, dll_name))
    actions.write(output, content)

    return output

def _should_output_ref_assembly(toolchain):
    return fsharp_ref_assemblies_are_deterministic(toolchain.dotnetinfo.sdk_version)

# buildifier: disable=unnamed-macro
def AssemblyAction(
        actions,
        compiler_wrapper,
        compiler_worker,
        label,
        debug,
        embed_sources,
        defines,
        deps,
        exports,
        targeting_pack,
        internals_visible_to,
        keyfile,
        langversion,
        resources,
        srcs,
        data,
        appsetting_files,
        compile_data,
        out,
        target,
        target_name,
        target_framework,
        version,
        toolchain,
        strict_deps,
        generate_documentation_file,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
        project_sdk,
        compiler_options,
        is_windows):
    """Creates an action that runs the F# compiler with the specified inputs.

    This macro aims to match the [F# compiler](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options), with the inputs mapping to compiler options.

    Args:
        actions: Bazel module providing functions to create actions.
        compiler_wrapper: The wrapper script that invokes the F# compiler.
        compiler_worker: The persistent worker to compile with, or None to fall back to the wrapper script.
        label: The label of the target. This is used to determine the relative path of embedded resources.
        debug: Emits debugging information.
        embed_sources: Embeds the sources in the PDB.
        defines: The list of conditional compilation symbols.
        deps: The list of other libraries to be linked in to the assembly.
        exports: List of exported targets.
        targeting_pack: The targeting pack being used.
        internals_visible_to: An optional list of assemblies that can see this assemblies internal symbols.
        keyfile: Specifies a strong name key file of the assembly.
        langversion: Specify language version: Default, ISO-1, ISO-2, 3, 4, 5, 6, 7, 7.1, 7.2, 7.3, or Latest
        resources: The list of resouces to be embedded in the assembly.
        srcs: The list of source (.cs) files that are processed to create the assembly.
        data: List of files that are a direct runtime dependency
        appsetting_files: List of appsettings files to include in the output.
        compile_data: List of files that are a direct compile time dependency
        target_name: A unique name for this target.
        out: Specifies the output file name.
        target: Specifies the format of the output file by using one of four options.
        target_framework: The target framework moniker for the assembly.
        version: The assembly version as a NuGet version string, or "" for none.
        toolchain: The toolchain that supply the F# compiler.
        strict_deps: Whether or not to use strict dependencies.
        generate_documentation_file: Whether or not to output XML docs for the compiled dll.
        treat_warnings_as_errors: Whether or not to treat warnings as errors.
        warnings_as_errors: List of warnings to treat as errors.
        warnings_not_as_errors: List of warnings to not treat errors.
        warning_level: The warning level to use.
        nowarn: List of warnings to suppress.
        project_sdk: The project SDK being targeted
        compiler_options: Additional compiler options to pass to the compiler.
        is_windows: Whether or not the target is running on Windows.

    Returns:
        The compile and runtime providers, and the static web assets the compile
        generated - always none, because F# compiles no Razor.
    """

    assembly_name = target_name if out == "" else out
    subsystem_version = get_framework_version_info(target_framework)
    (
        irefs,
        prefs,
        analyzers,
        analyzers_csharp,
        analyzers_fsharp,
        analyzers_vb,
        transitive_compile_data,
        framework_files,
        exports_files,
    ) = collect_compile_info(
        assembly_name,
        deps,
        targeting_pack,
        exports,
        strict_deps,
    )
    defines = framework_preprocessor_symbols(target_framework) + defines

    assembly_version_fs = _write_assembly_version_fsharp(actions, target_name, assembly_name, version)
    if assembly_version_fs:
        # First rather than last: a binary's entry point has to be in the last file.
        srcs = [assembly_version_fs] + srcs

    out_dir = target_name + "/" + target_framework
    out_ext = "dll"
    out_dll = actions.declare_file("%s/%s.%s" % (out_dir, assembly_name, out_ext))
    out_iref = None
    out_ref = actions.declare_file("%s/ref/%s.%s" % (out_dir, assembly_name, out_ext)) if _should_output_ref_assembly(toolchain) else None
    out_pdb = actions.declare_file("%s/%s.pdb" % (out_dir, assembly_name))
    out_xml = actions.declare_file("%s/%s.xml" % (out_dir, assembly_name)) if generate_documentation_file else None

    out_appsettings = copy_files_to_dir(target_name, actions, is_windows, appsetting_files, out_dir)

    if len(internals_visible_to) == 0:
        _compile(
            actions,
            compiler_wrapper,
            compiler_worker,
            label,
            debug,
            embed_sources,
            defines,
            keyfile,
            langversion,
            irefs,
            framework_files,
            resources,
            srcs,
            depset(compile_data, transitive = [transitive_compile_data]),
            subsystem_version,
            target,
            target_name,
            target_framework,
            toolchain,
            treat_warnings_as_errors,
            warnings_as_errors,
            warnings_not_as_errors,
            warning_level,
            nowarn,
            compiler_options,
            out_dll = out_dll,
            out_ref = out_ref,
            out_pdb = out_pdb,
            out_xml = out_xml,
        )
    else:
        # If the user is using internals_visible_to generate an additional
        # reference-only DLL that contains the internals. We want the
        # InternalsVisibleTo in the main DLL too to be less suprising to users.
        out_iref = actions.declare_file("%s/iref/%s.%s" % (out_dir, assembly_name, out_ext)) if _should_output_ref_assembly(toolchain) else None

        internals_visible_to_fs = _write_internals_visible_to_fsharp(
            actions,
            label_name = target_name,
            dll_name = assembly_name,
            others = internals_visible_to,
        )
        _compile(
            actions,
            compiler_wrapper,
            compiler_worker,
            label,
            debug,
            embed_sources,
            defines,
            keyfile,
            langversion,
            irefs,
            framework_files,
            resources,
            srcs + [internals_visible_to_fs],
            depset(compile_data, transitive = [transitive_compile_data]),
            subsystem_version,
            target,
            target_name,
            target_framework,
            toolchain,
            treat_warnings_as_errors,
            warnings_as_errors,
            warnings_not_as_errors,
            warning_level,
            nowarn,
            compiler_options,
            out_ref = out_iref,
            out_dll = out_dll,
            out_pdb = out_pdb,
            out_xml = out_xml,
        )

        if out_iref != None:
            # Generate a ref-only DLL without internals
            _compile(
                actions,
                compiler_wrapper,
                compiler_worker,
                label,
                debug,
                embed_sources,
                defines,
                keyfile,
                langversion,
                irefs,
                framework_files,
                resources,
                srcs,
                depset(compile_data, transitive = [transitive_compile_data]),
                subsystem_version,
                target,
                target_name,
                target_framework,
                toolchain,
                treat_warnings_as_errors,
                warnings_as_errors,
                warnings_not_as_errors,
                warning_level,
                nowarn,
                compiler_options,
                out_dll = None,
                out_ref = out_ref,
                out_pdb = None,
                out_xml = None,
            )

    return (DotnetAssemblyCompileInfo(
        name = assembly_name,
        version = version or DEFAULT_ASSEMBLY_VERSION,
        project_sdk = project_sdk,
        target_framework = target_framework,
        refs = [out_ref] if out_ref else [out_dll],
        irefs = [out_iref] if out_iref else [out_ref] if out_ref else [out_dll],
        analyzers = [],
        analyzers_csharp = [],
        analyzers_fsharp = [],
        analyzers_vb = [],
        internals_visible_to = internals_visible_to or [],
        compile_data = compile_data,
        exports = exports_files,
        transitive_refs = prefs,
        transitive_analyzers = analyzers,
        transitive_analyzers_csharp = analyzers_csharp,
        transitive_analyzers_fsharp = analyzers_fsharp,
        transitive_analyzers_vb = analyzers_vb,
        transitive_compile_data = transitive_compile_data,
    ), DotnetAssemblyRuntimeInfo(
        name = assembly_name,
        version = version or DEFAULT_ASSEMBLY_VERSION,
        libs = [out_dll],
        resource_assemblies = [],
        pdbs = [out_pdb] if out_pdb else [],
        xml_docs = [out_xml] if out_xml else [],
        data = data,
        appsetting_files = depset(out_appsettings),
        native = [],
        deps = depset([dep[DotnetAssemblyRuntimeInfo] for dep in deps], transitive = [dep[DotnetAssemblyRuntimeInfo].deps for dep in deps]),
        nuget_info = None,
        direct_deps_depsjson_fragment = {dep[DotnetAssemblyRuntimeInfo].name: dep[DotnetAssemblyRuntimeInfo].version for dep in deps},
    ), [])

def _compile(
        actions,
        compiler_wrapper,
        compiler_worker,
        label,
        debug,
        embed_sources,
        defines,
        keyfile,
        langversion,
        refs,
        framework_files,
        resources,
        srcs,
        compile_data,
        subsystem_version,
        target,
        target_name,
        target_framework,
        toolchain,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
        compiler_options,
        out_dll = None,
        out_ref = None,
        out_pdb = None,
        out_xml = None):
    # Our goal is to match msbuild as much as reasonable
    # https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options
    args = actions.args()
    args.add("--noframework")
    args.add("--utf8output")
    args.add("--deterministic+")
    args.add("--nowin32manifest")
    args.add("--nocopyfsharpcore")
    args.add("--simpleresolution")
    args.add(_format_targetprofile(target_framework))
    args.add("--nologo")

    if use_highentropyva(target_framework):
        args.add("--highentropyva+")
    else:
        args.add("--highentropyva-")

    if subsystem_version != None:
        args.add("--subsystemversion:" + subsystem_version)

    generate_warning_args(
        args,
        treat_warnings_as_errors,
        warnings_as_errors,
        warnings_not_as_errors,
        warning_level,
        nowarn,
    )

    args.add("--target:" + target)

    # MSBuild passes no --langversion for F#, letting fsc default to latest.
    if langversion:
        args.add("--langversion:" + langversion)

    if debug:
        args.add("--debug+")
        args.add("--optimize-")
        args.add("--define:TRACE")
        args.add("--define:DEBUG")
        args.add("--tailcalls-")
    else:
        args.add("--debug-")
        args.add("--optimize+")
        args.add("--define:TRACE")
        args.add("--define:RELEASE")

    args.add("--debug:portable")

    # A PDB records execroot-relative document paths, which resolve to nothing
    # once the build is over. `--embed+` puts the sources in the symbols instead.
    # See docs/README.md#embedded-sources.
    if embed_sources:
        args.add("--embed+")

    # outputs
    if out_dll != None:
        args.add(out_dll, format = "--out:%s")
        args.add(out_pdb, format = "--pdb:%s")
        outputs = [out_dll, out_pdb]

        if out_ref != None:
            args.add(out_ref, format = "--refout:%s")
            outputs.append(out_ref)

    else:
        args.add("--refonly")
        args.add(out_ref, format = "--out:%s")
        outputs = [out_ref]

    if out_xml != None:
        args.add(out_xml, format = "--doc:%s")
        outputs.append(out_xml)

    # assembly references
    # fsc resolves a duplicate assembly identity by order, so refs must come
    # before the framework files.
    format_ref_arg(args, depset(transitive = [refs, framework_files]))

    # .fs files
    args.add_all(srcs)

    # resources
    add_resource_args(args, resources, label, out_dll.basename if out_dll != None else None, "fsharp")

    # defines
    args.add_all(defines, format_each = "-d:%s")

    # keyfile
    if keyfile != None:
        args.add(keyfile, format = "--keyfile:%s")

    # Additional compiler options
    for option in compiler_options:
        args.add(option)

    # spill to a "response file" when the argument list gets too big (Bazel
    # makes that call based on limitations of the OS).
    args.set_param_file_format("multiline")

    args.use_param_file("@%s", use_always = True)

    direct_inputs = srcs + resources
    direct_inputs += [keyfile] if keyfile else []

    icu_arguments, icu_tools = [], []
    if compiler_worker:
        executable = compiler_worker
        extra_tools = []
        execution_requirements = {
            "requires-worker-protocol": "json",
            "supports-path-mapping": "1",
            "supports-workers": "1",
        }
    else:
        executable = compiler_wrapper
        extra_tools = [compiler_wrapper]
        execution_requirements = {"supports-path-mapping": "1"}

        icu_arguments, icu_tools = icu_wrapper_arguments(actions, toolchain)

    actions.run(
        mnemonic = "FSharpCompile",
        progress_message = "Compiling " + target_name + (" (internals ref-only dll)" if out_dll == None else ""),
        inputs = depset(
            direct = direct_inputs,
            transitive = [framework_files, refs, compile_data],
        ),
        tools = depset(
            direct = extra_tools + [
                toolchain.compiler_host.files_to_run.executable,
                toolchain.fsharp_compiler.files_to_run.executable,
            ],
            transitive = icu_tools + [
                toolchain.compiler_host.default_runfiles.files,
                toolchain.fsharp_compiler.default_runfiles.files,
            ],
        ),
        outputs = outputs,
        executable = executable,
        arguments = icu_arguments + [
            toolchain.compiler_host.files_to_run.executable.path,
            toolchain.fsharp_compiler.files_to_run.executable.path,
            args,
        ],
        env = dicts.add(
            {"DOTNET_CLI_HOME": toolchain.compiler_host.files_to_run.executable.dirname},
            globalization_env(toolchain),
        ),
        execution_requirements = execution_requirements,
    )
