"""Helpers for generated C# global usings."""

SDK_IMPLICIT_GLOBAL_USINGS = [
    "System",
    "System.Collections.Generic",
    "System.IO",
    "System.Linq",
    "System.Net.Http",
    "System.Threading",
    "System.Threading.Tasks",
]

def normalize_global_using(value):
    normalized = value.strip()
    if normalized.startswith("global using "):
        normalized = normalized[len("global using "):].strip()
    if normalized.endswith(";"):
        normalized = normalized[:-1].strip()
    if not normalized:
        fail("global_usings entries must not be empty")
    return normalized

def dedupe_global_usings(values):
    result = []
    seen = {}
    for value in values:
        if value not in seen:
            seen[value] = True
            result.append(value)
    return result

def collect_global_usings(global_usings, implicit_usings, inherited_global_usings):
    result = list(inherited_global_usings)
    if implicit_usings:
        result.extend(SDK_IMPLICIT_GLOBAL_USINGS)
    result.extend([normalize_global_using(global_using) for global_using in global_usings])
    return dedupe_global_usings(result)

def generate_global_usings_source(actions, output_path, global_usings):
    if len(global_usings) == 0:
        return []

    output = actions.declare_file(output_path)
    lines = ["// <auto-generated/>"]
    for global_using in global_usings:
        lines.append("global using " + global_using + ";")

    actions.write(
        output = output,
        content = "\n".join(lines) + "\n",
    )
    return [output]
