"""Create a repository to hold the toolchains

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"
Note that in order to resolve toolchains in the analysis phase
Bazel needs to analyze all toolchain targets that are registered.
Bazel will not need to analyze all targets referenced by toolchain.toolchain attribute.
If in order to register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets
from the repository with dotnet_toolchain targets.
Former will be always fetched,
and the latter will only be fetched when user actually needs to build dotnet code.
"
The "complex computation" in our case is simply downloading large artifacts.
This guidance tells us how to avoid that: we put the toolchain targets in the alias repository
with only the toolchain attribute pointing into the platform-specific repositories.
"""

# The toolchain type an SDK registers for: `DOTNET_TOOLCHAIN_TYPE` for the SDK
# the user builds with, `BOOTSTRAP_TOOLCHAIN_TYPE` for the one rules_dotnet
# builds its own tools with.
DOTNET_TOOLCHAIN_TYPE = "@rules_dotnet//dotnet:toolchain_type"
BOOTSTRAP_TOOLCHAIN_TYPE = "@rules_dotnet//dotnet:bootstrap_toolchain_type"

# Add more platforms as needed to mirror all the binaries
# published by the upstream project.
PLATFORMS = {
    "x86_64-apple-darwin": struct(
        os = "osx",
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "aarch64-apple-darwin": struct(
        os = "osx",
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "x86_64-unknown-linux-gnu": struct(
        os = "linux",
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "arm64-unknown-linux-gnu": struct(
        os = "linux",
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:arm64",
        ],
    ),
    "x86_64-pc-windows-msvc": struct(
        os = "windows",
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
    "arm64-pc-windows-msvc": struct(
        os = "windows",
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:arm64",
        ],
    ),
}

def _toolchains_repo_impl(repository_ctx):
    build_content = """# Generated by toolchains_repo.bzl
#
# These are registered by the `dotnet` module extension, or can be passed to the
# --extra_toolchains flag, so you don't normally need to interact with them.
"""

    for [platform, meta] in PLATFORMS.items():
        build_content += """
# Declare a toolchain Bazel will select for running the tool in an action
# on the execution platform.
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{sdk_repository_name}_{platform}//:dotnet_toolchain",
    toolchain_type = "{toolchain_type}",
)
""".format(
            platform = platform,
            sdk_repository_name = repository_ctx.attr.sdk_repository_name,
            compatible_with = meta.compatible_with,
            toolchain_type = repository_ctx.attr.toolchain_type,
        )

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "toolchain_type": attr.string(
            doc = "The toolchain type the generated `toolchain` targets register for.",
            default = DOTNET_TOOLCHAIN_TYPE,
        ),
        "sdk_repository_name": attr.string(
            doc = "Base name of the per-platform repositories holding the SDK these toolchains point at.",
        ),
    },
)
